config/routes.rb
Doers::Application.routes.draw do
  # Easy Auth endpoints
  # Allow only Angel List to avoid exceptions.
  constraints(:provider => :angel_list) do
    easy_auth_routes
  end

  get 'sign_in' => 'sessions#index'

  resources :profiles, :only => [:show, :update, :edit] do
    get :mine, :on => :collection
    constraints :profile_id => :mine do
      get :notifications
      patch :notifications
    end
  end
  resource :pages, :only => [], :path => '/' do
    get :dashboard
    get :waiting
    patch :waiting
    get :export
    get :download
    get :stats
  end

  namespace :api, :constraints => {:format => :json} do
    namespace :v1 do
      resources(:users, :only => [:index, :show])
      resources(:projects)
      resources(:startups, :only => [:create, :index])
      resources(:boards)
      resources(:cards)
      resources(:assets)
      resources(:teams, :only => [:index, :show])
      resources(:embeds, :only => [:index])
      resources(:activities, :except => [:create, :update])
      resources(:updates, :only => [:index])
      resources(:invitations, :except => [:update])
      resources(:memberships, :only => [:index, :show, :update, :destroy])
      resources(:comments, :except => [:update])
      resources(:topics)
      resources(:endorses, :except => [:update])
      resources(:whiteboards)
    end
  end

  root :to => 'pages#dashboard'
end

app/views/pages/dashboard.html.haml
= content_for(:footer_embed, javascript_include_tag('doers'))

#doers-app

app/views/pages/export.html.haml
.wrapper
  .page
    - if @current_account.boards.count
      %h1
        = _('Your export options')
      %p
        = _('Below you can queue your project boards data for download.')
      %p
        = _('You will get an email with a package with boards content archived.')
        = _('There will be two files for each board, one computer friendly (JSON), and the other one human friendly (Markdown).')
      %p
        %a#export-btn{:href => download_pages_path}
          %button.button
            %span.icon.icon-arrow-down
            = _('Email me boards data')
    - else
      %h1
        = _('No export options for you')
      %p
        = _('Export is not available for you since there are no boards you have created.')
      %p
        %a{:href => root_path}
          %button.button
            %span.icon.icon-arrow-prev
            = _('Take me back to dashboard')

app/views/pages/stats.html.haml
- content_for :footer_embed, javascript_include_tag('stats')

.wrapper
  .page
    %h1
      = _('Daily Stats')

    %h3
      = _('Daily Users')
    %p
      %canvas#daily-users{:width => '920', :height => '300' }
      %small
        Activated users are green. Subscribers are red.

    %h3
      = _('Daily Projects')
    %p
      %canvas#daily-projects{:width => '920', :height => '300' }
      %small
        Manually created projects are green. Imported are red.

    %h3
      = _('Daily Boards')
    %p
      %canvas#daily-boards{:width => '920', :height => '300' }

    %h3
      = _('Daily Topics')
    %p
      %canvas#daily-topics{:width => '920', :height => '300' }
      %small
        Aligned topics are green. Unaligned topics are red.

    %h3
      = _('Daily Suggestions')
    %p
      %canvas#daily-suggestions{:width => '920', :height => '300' }

    %h3
      = _('Daily Comments')
    %p
      %canvas#daily-comments{:width => '920', :height => '300' }

    %h3
      = _('Daily Activities')
    %p
      %canvas#daily-activities{:width => '920', :height => '300' }
      %small
        Endorses are green. The rest is red.

app/views/pages/waiting.html.haml
.wrapper
  .page
    %h1
      = _('Claim your beta access with the promo code.')
    %p
      = _('We sent promo codes to a close circle of people we know.')
      = _('These codes can be used to instantly claim beta access.')
    %p
      = _('If you got an email with such a promo code, you can claim it below:')

    = form_for(current_account, :url => waiting_pages_path) do |f|
      %p
        = f.text_field :promo_code, :placeholder => _('Promo code goes here...')
      %p
        = _('We are looking to have a diverse group of beta customers.')
        = _('So in order to facilitate for us the process, please choose your status below:')
      %p
        = f.select :interest, User::INTERESTS
      %p
        = f.check_box :newsletter_allowed?
        = f.label :newsletter_allowed, _('Please email me news sometimes.')
      %p
        = f.button :class => 'button' do
          %span.icon.icon-checkmark
          = _('Claim')