config/routes.rb
Doers::Application.routes.draw do
  # Easy Auth endpoints
  # Allow only Angel List to avoid exceptions.
  constraints(:provider => :angel_list) do
    easy_auth_routes
  end

  get 'sign_in' => 'sessions#index'

  resources :profiles, :only => [:show, :update, :edit] do
    get :mine, :on => :collection
    constraints :profile_id => :mine do
      get :notifications
      patch :notifications
    end
  end
  resource :pages, :only => [], :path => '/' do
    get :dashboard
    get :waiting
    patch :waiting
    get :export
    get :download
    get :stats
  end

  namespace :api, :constraints => {:format => :json} do
    namespace :v1 do
      resources(:users, :only => [:index, :show])
      resources(:projects)
      resources(:startups, :only => [:create, :index])
      resources(:boards)
      resources(:cards)
      resources(:assets)
      resources(:teams, :only => [:index, :show])
      resources(:embeds, :only => [:index])
      resources(:activities, :except => [:create, :update])
      resources(:updates, :only => [:index])
      resources(:invitations, :except => [:update])
      resources(:memberships, :only => [:index, :show, :update, :destroy])
      resources(:comments, :except => [:update])
      resources(:topics)
      resources(:endorses, :except => [:update])
      resources(:whiteboards)
    end
  end

  root :to => 'pages#dashboard'
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title
      = content_for?(:title) ? yield(:title) : _('Welcome')
      &bull;
      = Doers::Config.app_name

    = favicon_link_tag(image_path('favicon.ico'), :type => 'image/x-icon', :rel => 'shortcut icon')

    %meta{ :charset => 'utf-8' }
    %meta{ 'http-equiv' => 'X-UA-Compatible', :content => 'IE=edge,chrome=1' }
    %meta{ :name => 'viewport', :content => 'width=device-width' }
    %meta{ :name => :generator, :content => Doers::Config.app_id }

    /[if lt IE 9]
      %script{ :src => 'http://html5shiv.googlecode.com/svn/trunk/html5.js' }

    / Typekit
    %script{ :src => '//use.typekit.net/mtd8kej.js' }
    :javascript
      try{Typekit.load();}catch(e){}

    = stylesheet_link_tag 'application'
    = yield(:head_embed) if content_for?(:head_embed)
    = csrf_meta_tags

  %body
    = render('shared/alerts')
    = render('shared/nav')
    .content
      = yield

    = javascript_include_tag 'application'
    = yield(:footer_embed) if content_for?(:footer_embed)

app/views/layouts/notification.html.haml
!!! 5
%html
  %head
    %title
      = Doers::Config.app_name
    %meta{ :charset => 'utf-8' }

  %body
    %h1
      = _('Hi %s,') % @user.nicename
    = yield
    .footer
      %p
        = link_to _('Manage notifications'), profile_notifications_url(:mine)
      %p
        = _('Thanks.')
        %br/
        = _('Your')
        = link_to Doers::Config.app_name, root_url
        = _('team.')